@startuml "Bike1"


class Station{
  id: String
  name: String
  latitude: String
  longitude: String
  dockCount: String
  city: String
  installationDate: String
}

class Status{
  bikesAvailable: Int
  docksAvailable: Int
  time: Int
}

class Trip{
  id: String
  duration: String
  startDate: String
  startStationName: String
  startStationId: String
  endDate: String
  endStationName: String
  endStationId: String
  bikeId: String
  subscriptionType: String
  zipCode: String
}

class Weather{
  date: Int
  maxTemperatureF: Int
  meanTemperatureF: Int
  minTemperatureF: Int
  maxDewPointF: Int
  meanDewPointF: Int
  minDewPointF: Int
  maxHumidity: Int
  meanHumidity: Int
  minHumidity: Int
  maxSeaLevelPressureInches: Int
  meanSeaLevelPressureInches: Int
  minSeaLevelPressureInches: Int
  maxVisibilityMiles: Int
  meanVisibilityMiles: Int
  minVisibilityMiles: Int
  maxWindSpeedMph: Int
  meanWindSpeedMph: Int
  maxGustSpeedMph: Int
  precipitationInches: Int
  cloudCover: Int
  events: Int
  windDirDegrees: Int
  zipCode: Int
}



Station "1" -- "*" Status


@enduml