@startuml "Dorm1"


class Student{
  studentId: String
  lastName: String
  firstName: String
  age: String
  sex: String
  major: String
  advisor: String
  cityCode: String
}

class Dorm{
  dormId: Int
  dormName: Int
  studentCapacity: Int
  gender: Int
}

class DormAmenity{
  amenityId: String
  amenityName: String
}


class LivesIn{
  roomNumber: Int
}



Student "1" -- "*" LivesIn

Dorm "1" -- "*" LivesIn

Dorm "*" -- "*" DormAmenity


@enduml