@startuml "Ship1"


class Captain{
  captainId: String
  name: String
  age: String
  class: String
  rank: String
}

class Ship{
  shipId: String
  name: Int
  type: Int
  builtYear: Int
  class: Int
  flag: Int
}



Captain "*" -- "1" Ship


@enduml