# Generated by Django 4.0.5 on 2022-07-04 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='QClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('source', models.CharField(choices=[('W', 'WikiSQL'), ('S', 'Spider')], default='W', max_length=1)),
                ('qmodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='nl2ocl.qmodel')),
            ],
        ),
        migrations.CreateModel(
            name='QAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('qclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='nl2ocl.qclass')),
            ],
        ),
        migrations.CreateModel(
            name='QAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qmodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nl2ocl.qmodel')),
            ],
        ),
        migrations.CreateModel(
            name='QAssociate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nl2ocl.qassociation')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nl2ocl.qattribute')),
            ],
        ),
        migrations.CreateModel(
            name='NLQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('qmodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='nl2ocl.qmodel')),
            ],
        ),
    ]
