# Generated by Django 4.0.5 on 2022-07-04 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nl2ocl', '0002_alter_qattribute_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nlquestion',
            name='question',
            field=models.TextField(),
        ),
    ]
