# Generated by Django 4.0.5 on 2022-07-04 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nl2ocl', '0005_nlquestion_query'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qclass',
            name='source',
        ),
        migrations.AddField(
            model_name='qmodel',
            name='source',
            field=models.CharField(choices=[('W', 'WikiSQL'), ('S', 'Spider')], default='W', max_length=1),
        ),
    ]
