# Generated by Django 4.0.5 on 2022-07-06 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nl2ocl', '0007_alter_nlquestion_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='qassociate',
            name='source',
            field=models.CharField(choices=[('1', 'FK'), ('*', 'RV')], default='1', max_length=2),
        ),
    ]
