# Generated by Django 4.0.5 on 2022-07-06 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nl2ocl', '0008_qassociate_source'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qassociate',
            old_name='source',
            new_name='rol',
        ),
    ]
