# Generated by Django 4.0.5 on 2022-07-06 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nl2ocl', '0009_rename_source_qassociate_rol'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qassociate',
            old_name='rol',
            new_name='role',
        ),
    ]
