# Generated by Django 4.0.5 on 2022-07-09 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nl2ocl', '0011_alter_qassociate_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='OCLTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation', models.TextField(default=None, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.BooleanField(default=True)),
                ('nlquestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translation', to='nl2ocl.nlquestion')),
            ],
        ),
    ]
