# Generated by Django 4.0.5 on 2022-07-22 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nl2ocl', '0013_alter_ocltranslation_translation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ocltranslation',
            options={'ordering': ['-pk']},
        ),
        migrations.AddField(
            model_name='nlquestion',
            name='approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='nlquestion',
            name='user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ocltranslation',
            name='approved',
            field=models.BooleanField(default=True),
        ),
    ]
