# Generated by Django 4.0.5 on 2022-07-22 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nl2ocl', '0015_reportedquestion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportedquestion',
            old_name='reasson',
            new_name='reason',
        ),
    ]
